# 应用基础配置
# 此文件由系统初始化向导自动生成
# 生成时间: 2026-05-01 00:22:19

# 已初始化标记
initialized: true

app:
  name: "FastAPI-Vue-Admin"
  version: "1.0.7"
  host: "0.0.0.0"
  port: 9090
  env: "dev"
  api_prefix: "/api"
  reload: true
  api_status_enabled: true

jwt:
  algorithm: "HS256"
  secret_key: "4c305f1364ca251a831e02be6c764933ab47754c520fc63fea282fb21eb6c07f"
  salt: "fastapi-vue-admin"
  expire_minutes: 1440
  redis_expire_minutes: 30

database:
  engine: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  database: "fva"
  pool_size: 10
  pool_timeout: 30
  echo: false
  timezone: "Asia/Shanghai"
  charset: "utf8mb4"

redis:
  mode: "server"
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 1
  max_connections: 10
  socket_timeout: 5
  retry_on_timeout: true
